package org.tanzu.dataflow.streamapps.pgvectorsink;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.function.Consumer;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import org.springframework.ai.document.Document;
import org.springframework.ai.vectorstore.VectorStore;
import org.springframework.boot.context.properties.EnableConfigurationProperties;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.messaging.Message;

/**
 * Spring Cloud Stream consumer that writes text documents to PgVector.
 * Accepts messages containing text content and stores them using Spring AI's
 * {@link VectorStore} abstraction, which handles both embedding generation
 * and storage in a single operation.
 * <p>
 * Database credentials (PGVECTOR_URL, PGVECTOR_USERNAME, PGVECTOR_PASSWORD) and
 * embedding API key (EMBEDDING_API_KEY) are injected via CredHub service bindings
 * in VCAP_SERVICES at runtime.
 */
@Configuration
@EnableConfigurationProperties(PgVectorSinkProperties.class)
public class PgVectorSinkConfiguration {

    private static final Logger log = LoggerFactory.getLogger(PgVectorSinkConfiguration.class);

    @Bean
    public Consumer<Message<String>> writeToVectorStore(VectorStore vectorStore) {
        return message -> {
            String text = message.getPayload();
            log.debug("Writing document with {} characters to PgVector", text.length());

            Map<String, Object> metadata = new HashMap<>();
            if (message.getHeaders().containsKey("chunk-index")) {
                metadata.put("chunk-index", message.getHeaders().get("chunk-index"));
            }
            if (message.getHeaders().containsKey("chunk-count")) {
                metadata.put("chunk-count", message.getHeaders().get("chunk-count"));
            }
            if (message.getHeaders().containsKey("original-mime-type")) {
                metadata.put("original-mime-type", message.getHeaders().get("original-mime-type"));
            }

            Document document = Document.builder()
                    .text(text)
                    .metadata(metadata)
                    .build();

            vectorStore.add(List.of(document));
            log.debug("Successfully wrote document to PgVector (embedding generated by VectorStore)");
        };
    }
}
